export {default as Home} from "./Home"
export {default as Explore} from "./Explore"
export {default as Post} from "./Post"
export {default as Profile} from "./Profile"
export {default as Register} from "./Regis"
export {default as DetailPost} from "./DetailPost"
export {default as User} from "./UserProfile"